### PR TITLE
Fix beforeload for Android <= 7

### LINKED ISSUE #386: Error on Android 6 and 7 using plugin from master
I'm using the code from master in my plugin, to get the 'beforeload' option in my application.

Running on Pocophone F1 with Android 9, it runs just fine, but the same app crashes on Androids 6 and 7 (couldn't test for Android 8 yet). The error thrown in the logcat is:

12-28 17:52:32.574 E/AndroidRuntime( 9825): FATAL EXCEPTION: main
12-28 17:52:32.574 E/AndroidRuntime( 9825): Process: io.cordova.onofreapp, PID: 9825
12-28 17:52:32.574 E/AndroidRuntime( 9825): java.lang.NoSuchMethodError: No virtual method getWebViewClient()Landroid/webkit/WebViewClient; in class Landroid/webkit/WebView; or its super classes (declaration of 'android.webkit.WebView' appears in /system/framework/framework.jar:classes2.dex)
12-28 17:52:32.574 E/AndroidRuntime( 9825):     at org.apache.cordova.inappbrowser.InAppBrowser$2.run(InAppBrowser.java:265)
12-28 17:52:32.574 E/AndroidRuntime( 9825):     at android.os.Handler.handleCallback(Handler.java:751)
12-28 17:52:32.574 E/AndroidRuntime( 9825):     at android.os.Handler.dispatchMessage(Handler.java:95)
12-28 17:52:32.574 E/AndroidRuntime( 9825):     at android.os.Looper.loop(Looper.java:154)
12-28 17:52:32.574 E/AndroidRuntime( 9825):     at android.app.ActivityThread.main(ActivityThread.java:6776)
12-28 17:52:32.574 E/AndroidRuntime( 9825):     at java.lang.reflect.Method.invoke(Native Method)
12-28 17:52:32.574 E/AndroidRuntime( 9825):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
12-28 17:52:32.574 E/AndroidRuntime( 9825):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

Any ideas?

### PR DESCRIPTION
**Pull request by rgtk**
### Platforms affected
Android

### Motivation and Context
On Android <= 7, using `beforeload` would crash the application due to change of Android API.
Fixes #386 

### Description
If device is running Android <= 7, 

### Testing
I ran it on Android 7 and 9, create `WebViewClient` instead of trying on relying on `WebView#getWebViewClient()` which is not available in these versions.

### Checklist

- [x] I've run the tests to see all new and existing tests pass
- [x] I added automated test coverage as appropriate for this change
- Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`) **Already made a commit without such prefix. Squashing it during merge should solve the issue.**
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [x] I've updated the documentation if necessary

### CODE REVIEW

**Comment by rgtk** [comment]
Most of the work is thanks to @caioinova. They figured out solution in #386.

**Comment by clark-zhao-hs** [comment]
Any update on merging this PR? Facing the same issue. @rgtk

File: src/android/InAppBrowser.java [hunk 1]
```diff
@@ -262,7 +263,12 @@ else if (action.equals("loadAfterBeforeload")) {
                 @SuppressLint("NewApi")
                 @Override
                 public void run() {
-                    ((InAppBrowserClient)inAppWebView.getWebViewClient()).waitForBeforeload = false;
+                    if (android.os.Build.VERSION.SDK_INT <= android.os.Build.VERSION_CODES.N_MR1) {
```
Comment (wvengen) [inline src/android/InAppBrowser.java]: I would say `android.os.Build.VERSION.SDK_INT < android.os.Build.VERSION_CODES.O`, since the Android docs mention "added in API level 26".

File: src/android/InAppBrowser.java [hunk 2]
```diff
@@ -1184,7 +1190,9 @@ public boolean shouldOverrideUrlLoading(String url, String method) {
             boolean useBeforeload = false;
             String errorMessage = null;
 
-            if(beforeload.equals("yes")
+            if (beforeload.equals("yes") && method == null) {
+                useBeforeload = true;
+            }else if(beforeload.equals("yes")
```
Comment (wvengen) [inline src/android/InAppBrowser.java]: Does this mean `method` can be `null`?

Comment (rgtk) [reply src/android/InAppBrowser.java]: Yes, For Android 6 and below `shouldOverrideUrlLoading(WebView webView, String url)` is called and it calls this method with `method = null`.

File: src/android/InAppBrowser.java (hunk 1 above)
Comment (rgtk) [reply src/android/InAppBrowser.java]: Better indeed. Done.

**Comment by digistorm** [comment]
`customizableOptions` should include `BEFORELOAD` otherwise `post` and `get` will get cast to a `yes` or `no` value.

**Comment by rgtk** [comment]
@digistorm This PR handles yes/no values and is tested. Feel free to create another PR if you'd find it valuable.

**Comment by rgtk** [comment]
@wvengen Could it be merged then?

**Comment by rgtk** [comment]
@purplecabbage Would you find time to merge it?
