### PR TITLE
(ios): rename CDVWKProcessPoolFactory

### LINKED ISSUE #751: WKWebview cookie sometimes can't be get after upgrade to Cordova 6.1.0
# Bug Report

## Problem
Try to get the cookie of inappbrowser. But sometimes can't get correct cookie.
This issue happen after upgrade cordova to Cordova ios 6.1.0. and inappbrowser upgrade to 4.0.0
### What is expected to happen?

Use  blow code to get cookies in decidePolicyForNavigationAction of CDVWKInAppBrowser

WKHTTPCookieStore *wkWebViewCookieStore =[[[theWebView configuration] websiteDataStore] httpCookieStore];
 [wkWebViewCookieStore getAllCookies:^(NSArray* wkcookies) {
        for (NSHTTPCookie* cookie in wkcookies)
               {
                   NSLog(@"wk cookie name is %@",cookie.name);
               }
    }];

### What does actually happen?
Some times the wkcookies can't get the correct cookie.
And this issue not always happen,  but sometimes.   in my test ,50% percentage happen.

## Information

This issue not happen after downgrade the cordova ios to 5.1 and still use inappbrowser 4.0.0(after resolve some compile error).

### Command or Code

Please see above 

### Environment, Platform, Device

Cordova 9.0.0, Cordova ios 6.1.0, xcode 11.5. 
Iphone simulator(13.5) and Iphone X (13.5)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

### PR DESCRIPTION
**Pull request by NiklasMerz**
### Platforms affected
iOS

### Motivation and Context

CDVWKProcessPoolFactory was integrated from the WKWebView plugin with
the new name: CDVWebViewProcessPoolFactory

### Description

This fixes the import of the processpool factory for cordova-ios versions 6 or greater. The process pool is now part of cordova-ios and needs to be available public see: https://github.com/apache/cordova-ios/pull/1031

Closes #751 

### Checklist

- [ ] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [x] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

### CODE REVIEW

File: src/ios/CDVWKInAppBrowser.m [hunk 1]
```diff
@@ -19,8 +19,8 @@ Licensed to the Apache Software Foundation (ASF) under one
 
 #import "CDVWKInAppBrowser.h"
 
-#if __has_include("CDVWKProcessPoolFactory.h")
-#import "CDVWKProcessPoolFactory.h"
+#if __has_include(<Cordova/CDVWebViewProcessPoolFactory.h>)
```
Comment (dpogue) [inline src/ios/CDVWKInAppBrowser.m:22]: In theory, for maximum compatibility, you could try both options:

```
#if __has_include(<Cordova/CDVWebViewProcessPoolFactory.h>) // Cordova-iOS >=6
  #import <Cordova/CDVWebViewProcessPoolFactory.h>
#elif __has_include("CDVWKProcessPoolFactory.h") // Cordova-iOS <6 with WKWebView plugin
  #import "CDVWKProcessPoolFactory.h"
#endif
```

Comment (NiklasMerz) [reply src/ios/CDVWKInAppBrowser.m]: That makes sense since the requirements are just set to cordova-ios>5.1.0 in #823

**Review by timbru31 — APPROVED** [review]
LGTM, but obviously only if we merge in https://github.com/apache/cordova-ios/pull/1031 :)

**Comment by timbru31** [comment]
With Darryl's suggestion the milestone could be moved to a minor release I guess?

**Comment by NiklasMerz** [comment]
Yes the change is not breaking anymore. Looks like the next release will be major anyways and we don't have a minor milestone.

**Review by erisu — APPROVED** [review]

**Review by dpogue — APPROVED** [review]

**Comment by jcesarmobile** [comment]
since 4.1.0 introduced [breaking changes](https://github.com/apache/cordova-plugin-inappbrowser/issues/831) maybe we should do a minor release first that fixed that problem and then we can continue with the breaking changes.
But that would mean we need to rever the [merged breaking changes](https://github.com/apache/cordova-plugin-inappbrowser/pull/821) to be able to do a minor release

or we can continue with the major release as not supporting Xcode 10 is not a big issue since its builds are not accepted in the App Store

**Comment by NiklasMerz** [comment]
Yeah I was just thinking about when and how to release next. Maybe we should do a discuss thread on the list.

Personally I think I would go for a major release now. I would agree that supporting Xcode 10 should not be that important since Xcode 11 is required for the app store and the current release is even 12. We should reduce our workload and move forward with the limited time we have. 

@jcesarmobile Do you know issues or users about Xcode 10?

**Comment by jcesarmobile** [comment]
> @jcesarmobile Do you know issues or users about Xcode 10?


Don't understand the question, the issue on Xcode 10 is linked on my previous comment https://github.com/apache/cordova-plugin-inappbrowser/issues/831

The easy fix for users is to use Xcode 11 or newer to compile, if we wanted to support it a `#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 130000` macro should be used, but probably not worth it

**Comment by NiklasMerz** [comment]
I was just asking if you know about people having issues with this version. I personally always prioritize work if users are complaining and it's not just something that came up internally.

**Comment by jcesarmobile** [comment]
I created the issue and nobody has added the 👍  reaction to it, so I guess nobody was affected by it.

**Comment by NiklasMerz** [comment]
As this fix needs this PR to be released with cordova-ios https://github.com/apache/cordova-ios/pull/1031  I think we could wait for that or are there reasons to release inappbrowser now as 5.0.0? The milestone looks good.

**Comment by nmanikiran** [comment]
Hi @NiklasMerz 
i am facing issues with cookie sync between `wkwebview` & `InappBrowser` even after updating to `v5.0.0`
for more i logged an [issue](https://github.com/apache/cordova-plugin-inappbrowser/issues/877)
