### PR TITLE
Fix incorrect TypeScript typings

### LINKED ISSUE #514: Incorrect TypeScript typings in version 3.1.0
# Bug Report

## Problem

Since the change to type definitions here https://github.com/apache/cordova-plugin-inappbrowser/commit/a0c267fe36be9a97c974f73b9d2160eca54b9828 the project does not compile.

### What is expected to happen?

TypeScript project should compile without typings errors.

### What does actually happen?

TypeScript project compilation fails due to typings errors.

## Information

```
ERROR in /xyz/plugins/cordova-plugin-inappbrowser/types/index.d.ts(27,11):
TS2430: Interface 'InAppBrowser' incorrectly extends interface 'Window'.
  Types of property 'addEventListener' are incompatible.
    Type '(type: channel, callback: InAppBrowserEventListenerOrEventListenerObject) => void' is not assignable to type '{ <K extends "load" | "abort" | "afterprint" | "beforeprint" | "beforeunload" | "blur" | "canplay" | "canplaythrough" | "change" | "click" | "compassneedscalibration" | "contextmenu" | "dblclick" | ... 120 more ... | "unhandledrejection">(type: K, listener: (this: Window, ev: WindowEventMap[K]) => any, options?: boo...'.
      Types of parameters 'type' and 'type' are incompatible.
        Type '"statusTap"' is not assignable to type 'channel'.
```

Most likely due to the change whereby event listener types were extracted to a separate list of strings at the top of the file, however that list does not allow for an arbitrary `string`. PR incoming, need a ref number.

### Command or Code

Usual `npm` tasks to build a TS project.

### Environment, Platform, Device

macOS 10.14.6
node 10.16.0
npm 6.9.0

### Version information

```
    "cordova": "9.0.0",
    "cordova-android": "8.0.0",
    "cordova-plugin-inappbrowser": "3.0.0",
    "typescript": "3.5.3",
    "webpack": "4.38.0",
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

### PR DESCRIPTION
**Pull request by kamilbrk**
### Platforms affected

TypeScript based Cordova projects.

### Motivation and Context

Fixes #514.

### Description

There was a regression in 3.1.0 since 3.0.0, whereby typings did not allow for an arbitrary `string` type for event listeners. In case your TypeScript project contains anything else extending `Window`, it would cause the build to fail.

### Testing

Ran official 3.1.0 from apache, build failures as described in linked issue.
Ran this fork, build succeeds.

### Checklist

- [x] I've run the tests to see all new and existing tests pass (just eslint?)
- [ ] I added automated test coverage as appropriate for this change
- [ ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

### CODE REVIEW

File: types/index.d.ts [hunk 1]
```diff
@@ -6,7 +6,7 @@
 // Copyright (c) Microsoft Open Technologies Inc
 // Licensed under the MIT license.
 // TypeScript Version: 2.3
-type channel = "loadstart" | "loadstop" | "loaderror" | "exit" | "message";
+type channel = "loadstart" | "loadstop" | "loaderror" | "exit" | "message" | string;
```
Comment (timbru31) [inline types/index.d.ts]: this makes the type useless if we just use a `string`. Let's continue the discussion in #514 where I've added a question.

**Comment by kamilbrk** [comment]
Updated to an agreed solution in #514
